### ISSUE TITLE
Improve call widget

### ISSUE THREAD

**Issue by twinh** [twinh/wei#81]
## Resources

http://api.jquery.com/jQuery.ajax/
https://github.com/jquery/jquery/blob/master/src/ajax.js
https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js
https://github.com/jquery/jquery/blob/master/test/unit/ajax.js
## Todos
- <del>[ ] retry $widget->call($call);</del> wait for next time
- [x] add support for contentType
- [x] add test for decode data in diff types
- [x] add userAgent option
- <del> [ ] add socket type ?</del>
- [x] add referer
- [x] add any method support: GET, POST, PUT, DELETE, HEAD, ANY...
- [x] add cookie support
- [x] add Host support
- [x] refactor method and code style, add comment
- [x] add documentation
- [x] add string data support
- [x] add global option
