### ISSUE TITLE
Use exception code as HTTP status code ?

### ISSUE THREAD

**Issue by twinh** [twinh/wei#87]
## TODO
- [x] Find out whether any PHP libraries used exception code
- [x] Check if possiable to use exception code as HTTP status code
- [x] Add exception code detect in error widget
- [x] Removed NotFoundException, and DispatchBreakException
